### ISSUE TITLE
distribution is still hard (can't launch on Win11)

### ISSUE THREAD

**Issue by erikyuzwa** [PolyMarsDev/Twini-Golf#16]
Just came across your video on this - love it! High5 for the work and putting this together.

- Downloaded latest zip from Itch.io page
- Attempted to run binary
- Missing `libgcc_s_seh-1.dll`
- Missing `libstdc++-6.dll`
- Game execution halts there

![Screenshot 2022-01-01 093031](https://user-images.githubusercontent.com/962434/147855222-10a02094-9410-4883-aa44-875662bc7c91.png)

![Screenshot 2022-01-01 093131](https://user-images.githubusercontent.com/962434/147855224-9ac2bfeb-a19d-479d-85cb-f7d7dc88f902.png)

- I'll attempt to build the source in something like Visual Studio to see if that helps? 🤷

**Comment by milkydelta** [comment]
I think those are the names of the dlls for the c and c++ standard libraries that mingw uses.  The solution there would be either finding the dlls in the mingw bin folder and copying them to the folder with the exe, adding the mingw bin folder to the windows path environment variable, or compiling with the -static-libstdc++  and -static-libgcc gcc compiler flags.

**Comment by milkydelta** [comment]
I just tried it on my computer and if you copy over both libstdc++-6.dll and libgcc_s_seh-1.dll then it gives a much more vague "the application was unable to start" error. I forgot that it also needs the mingw pthreads library, which is in the mingw bin folder as "libwinpthread-1.dll"

**Comment by erikyuzwa** [comment]
thanks! I'll try that out - thanks so much for the assistance!
